---
abstract: 'send notifications to your iPhone.'
author:
  - 'Yann Kerherve <yannk@cpan.org>'
build_requires:
  ExtUtils::MakeMaker: 6.42
  Test::More: 0
configure_requires:
  ExtUtils::MakeMaker: 6.42
distribution_type: module
generated_by: 'Module::Install version 1.00'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Net-AppNotifications
no_index:
  directory:
    - inc
    - t
    - xt
requires:
  AnyEvent: 0
  AnyEvent::HTTP: 0
  Find::Lib: 0
  URI: 0
  perl: 5.8.1
resources:
  homepage: http://github.com/yannk/perl-net-appnotifications/tree
  license: http://dev.perl.org/licenses/
  repository: git://github.com/yannk/perl-net-appnotifications.git
version: 0.02
